language: go

go:
- '1.11.x'

install:
- curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

script:
- env
- dep ensure -v
- rm -rf "$GOPATH/pkg/dep/sources"

deploy:
- provider: script
  script: bash deploy.sh
  on:
    branch: master
