language: go

go:
- '1.11.x'

install:
- curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

script:
- dep ensure -v

deploy:
- provider: script
  script: bash deploy.sh
  on:
    branch: master
